-- SAVE FIRST, PROCESS SECOND for the join forms.
-- Every submission is first stored as a plain copy of the answers in
-- join_applications. The member / student / membership form are then created
-- from that copy. If that step fails, the copy stays safe with the error
-- recorded, and staff can complete it from the Forms page.
-- Requires submit_join_application (already installed). Safe to run again.

create table if not exists public.join_applications (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  form_type text,
  applicant_name text,
  email text,
  payload jsonb not null,             -- { member, student, form } exactly as submitted
  status text not null default 'received'
    check (status in ('received', 'completed', 'failed', 'dismissed')),
  error text,
  attempts int not null default 0,
  member_id uuid,
  completed_at timestamptz,
  completed_by uuid
);

alter table public.join_applications enable row level security;

-- Staff can read and update; nobody writes directly (the functions below do)
drop policy if exists join_applications_staff_read on public.join_applications;
create policy join_applications_staff_read on public.join_applications for select
  using (exists (select 1 from members where auth_id = auth.uid() and role in ('admin', 'captain', 'coach', 'leader')));
drop policy if exists join_applications_staff_update on public.join_applications;
create policy join_applications_staff_update on public.join_applications for update
  using (exists (select 1 from members where auth_id = auth.uid() and role in ('admin', 'captain', 'coach', 'leader')));

-- Internal: try to turn a saved application into member + student + form
create or replace function public.process_join_application(p_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_app join_applications;
  v_member_id uuid;
begin
  select * into v_app from join_applications where id = p_id for update;
  if not found then return jsonb_build_object('status', 'missing'); end if;
  if v_app.status = 'completed' then
    return jsonb_build_object('status', 'completed', 'member_id', v_app.member_id);
  end if;

  begin
    v_member_id := submit_join_application(v_app.payload->'member', v_app.payload->'student', v_app.payload->'form');
    update join_applications
      set status = 'completed', member_id = v_member_id, error = null,
          attempts = attempts + 1, completed_at = now(), completed_by = auth.uid()
      where id = p_id;
    return jsonb_build_object('status', 'completed', 'member_id', v_member_id);
  exception when others then
    update join_applications
      set status = 'failed', attempts = attempts + 1,
          error = case when sqlerrm = 'ALREADY_REGISTERED'
                       then 'Already registered: a member with this name and date of birth already has a student record.'
                       else sqlerrm end
      where id = p_id;
    return jsonb_build_object('status', 'failed', 'error', sqlerrm);
  end;
end;
$$;
revoke all on function public.process_join_application(uuid) from public, anon, authenticated;

-- Called by the join forms. Saves the answers FIRST, then processes them.
-- p_id is generated by the app, so a retried request never saves twice.
create or replace function public.receive_join_application(
  p_id uuid, p_form_type text, p_member jsonb, p_student jsonb, p_form jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into join_applications (id, form_type, applicant_name, email, payload)
  values (
    p_id, p_form_type,
    trim(coalesce(p_member->>'first_name', '') || ' ' || coalesce(p_member->>'last_name', '')),
    p_member->>'email',
    jsonb_build_object('member', p_member, 'student', p_student, 'form', p_form)
  )
  on conflict (id) do nothing;

  -- The saved copy above is kept even if processing fails
  return process_join_application(p_id);
end;
$$;
grant execute on function public.receive_join_application(uuid, text, jsonb, jsonb, jsonb) to anon, authenticated;

-- Staff: complete (retry) a saved application, e.g. after a failure.
-- Optionally pass corrected answers in p_payload.
create or replace function public.complete_join_application(p_id uuid, p_payload jsonb default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from members where auth_id = auth.uid() and role in ('admin', 'captain', 'coach', 'leader')) then
    raise exception 'Not allowed';
  end if;
  if p_payload is not null then
    update join_applications set payload = p_payload where id = p_id and status <> 'completed';
  end if;
  update join_applications set status = 'received' where id = p_id and status in ('failed', 'dismissed');
  return process_join_application(p_id);
end;
$$;
grant execute on function public.complete_join_application(uuid, jsonb) to authenticated;
